import 'reflect-metadata'
import { getFromContainer, MetadataStorage } from 'class-validator'
import { getMetadataArgsStorage } from 'routing-controllers'
import { generateSwagger } from 'routing-controllers-openapi-extended'

import { UsersController } from './UsersController'

const routingControllersOptions = {
  controllers: [UsersController],
  routePrefix: '/api'
}
const metadatas = (getFromContainer(MetadataStorage) as any).validationMetadatas
const storage = getMetadataArgsStorage()
const spec = generateSwagger(storage, routingControllersOptions, metadatas, {
  info: {
    description: 'Generated by script',
    title: 'A sample API',
    version: '1.0.0'
  }
});

console.log(JSON.stringify(spec, undefined, 2));
